/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import codigo.Empresa;
import com.sun.corba.se.spi.oa.OADefault;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduar
 */
public class ComparacionGeneral extends javax.swing.JDialog {

    DefaultTableModel modeloTabla1 = new DefaultTableModel();
    DefaultTableModel modeloTabla2 = new DefaultTableModel();
    
    int intercambiosBurbuja=0;
    int comparacionesBurbuja=0;
    
    int intercambiosInsersion=0;
    int comparacionesInsersiont=0;
    
    int intercambiosSeleccion=0;
    int comparacionesSeleccion=0;
    
    int intercambiosQuickSort=0;
    int comparacionesQuickSort=0;
    public ComparacionGeneral(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        cargarModeloTabla1();
        cargarModeloTabla2();
        initComponents();
        labelComparacionQuick.setText("#Comparaciones: "+comparacionesQuickSort);
        labelIntercambiosQuick.setText("#Intercambios: "+intercambiosQuickSort);
        
        labelComparacionBurbuja.setText("#Comparaciones: "+comparacionesBurbuja);
        labelIntercambiosBurbuja.setText("#Intercambios: "+intercambiosBurbuja);
        
        labelComparacionInsersion.setText("#Comparaciones: "+comparacionesInsersiont);
        labelIntercambiosInsersion.setText("Intercambios: "+intercambiosInsersion);
        
        labelComparacionSeleccion.setText("#Comparaciones: "+comparacionesSeleccion);
        labelIntercambiosSeleccion.setText("#Intercambios: "+intercambiosSeleccion);
        
        
        setLocationRelativeTo(null);
    }
    
    private void cargarModeloTabla1(){
        modeloTabla1.addColumn("Codigo de empleado");
        modeloTabla1.addColumn("Nombre del empleado");
        modeloTabla1.addColumn("Sueldo de empleado");
        leerTexto();
    }
    
    private void cargarModeloTabla2(){
        modeloTabla2.addColumn("Codigo de empleado");
        modeloTabla2.addColumn("Nombre del empleado");
        modeloTabla2.addColumn("Sueldo de empleado");
        leerTexto2();
    }
    
    
    private void leerTexto(){
        Empresa empresa1=new Empresa();
        for (int i = 0; i < empresa1.getNUMERO_EMPLEADOS(); i++) {
            String[] empleado={Integer.toString(empresa1.getCodigoDelEmpleado(i)),empresa1.getNombreDelEmpleado(i),Float.toString(empresa1.getSueldoDelEmpleado(i))};
            modeloTabla1.addRow(empleado);
        }
    }
    
     private void leerTexto2(){
        Empresa empresa1=new Empresa();
        Empresa.setComparacionesQuickSort(0);
        Empresa.setIntercambiosQuickSort(0);
        empresa1.MetodoQuickSort();
        for (int i = 0; i < empresa1.getNUMERO_EMPLEADOS(); i++) {
            String[] empleado={Integer.toString(empresa1.getCodigoDelEmpleado(i)),empresa1.getNombreDelEmpleado(i),Float.toString(empresa1.getSueldoDelEmpleado(i))};
            modeloTabla2.addRow(empleado);
            comparacionesQuickSort=Empresa.getComparacionesQuickSort();
            intercambiosQuickSort=Empresa.getIntercambiosQuickSort();
        }
        Empresa empresa2=new Empresa();
        empresa2.OrdenBurbuja();
        comparacionesBurbuja=empresa2.getComparaciones();
        intercambiosBurbuja=empresa2.getIntercambios();
        
        Empresa empresa3=new Empresa();
        empresa3.OrdenInsercionDirecta();
        comparacionesInsersiont=empresa3.getComparaciones();
        intercambiosInsersion=empresa3.getIntercambios();
        
        Empresa empresa4=new Empresa();
        empresa4.OrdenSeleccionDirecta();
        comparacionesSeleccion=empresa4.getComparaciones();
        intercambiosSeleccion=empresa4.getIntercambios();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelIntercambiosBurbuja = new javax.swing.JLabel();
        labelComparacionInsersion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelComparacionBurbuja = new javax.swing.JLabel();
        labelIntercambiosInsersion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelComparacionSeleccion = new javax.swing.JLabel();
        labelIntercambiosSeleccion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelComparacionQuick = new javax.swing.JLabel();
        labelIntercambiosQuick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ORDENANDO POR CODIGO DE TRABAJADOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jTable1.setModel(modeloTabla2);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 460, 350));

        jTable2.setModel(modeloTabla1);
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 500, 350));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("ORDENADO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("SIN ORDENAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 710, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COMPARANDO EFICIENCIA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 330, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("EFICIENCIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, -1, -1));

        labelIntercambiosBurbuja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelIntercambiosBurbuja.setText("#Intercambios:  ");
        jPanel1.add(labelIntercambiosBurbuja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 230, -1));

        labelComparacionInsersion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelComparacionInsersion.setText("#Comparaciones: ");
        jPanel1.add(labelComparacionInsersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 230, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("METODO QUICK-SORT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("METODO BURBUJA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        labelComparacionBurbuja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelComparacionBurbuja.setText("#Comparaciones: ");
        jPanel1.add(labelComparacionBurbuja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 230, -1));

        labelIntercambiosInsersion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelIntercambiosInsersion.setText("#Intercambios:  ");
        jPanel1.add(labelIntercambiosInsersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("EFICIENCIA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("METODO INSERCION");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("EFICIENCIA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, -1));

        labelComparacionSeleccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelComparacionSeleccion.setText("#Comparaciones: ");
        jPanel1.add(labelComparacionSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 230, -1));

        labelIntercambiosSeleccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelIntercambiosSeleccion.setText("#Intercambios:  ");
        jPanel1.add(labelIntercambiosSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 230, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("METODO SELECCION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("EFICIENCIA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, -1, -1));

        labelComparacionQuick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelComparacionQuick.setText("#Comparaciones: ");
        jPanel1.add(labelComparacionQuick, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 610, 230, -1));

        labelIntercambiosQuick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelIntercambiosQuick.setText("#Intercambios:  ");
        jPanel1.add(labelIntercambiosQuick, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComparacionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComparacionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComparacionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComparacionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComparacionGeneral dialog = new ComparacionGeneral(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelComparacionBurbuja;
    private javax.swing.JLabel labelComparacionInsersion;
    private javax.swing.JLabel labelComparacionQuick;
    private javax.swing.JLabel labelComparacionSeleccion;
    private javax.swing.JLabel labelIntercambiosBurbuja;
    private javax.swing.JLabel labelIntercambiosInsersion;
    private javax.swing.JLabel labelIntercambiosQuick;
    private javax.swing.JLabel labelIntercambiosSeleccion;
    // End of variables declaration//GEN-END:variables
}
