/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import codigo.Empresa;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduar
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    DefaultTableModel modeloTabla = new DefaultTableModel();
    public VentanaPrincipal() {
        this.setUndecorated(true);
        cargarModeloTabla();
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void cargarModeloTabla(){
        modeloTabla.addColumn("Codigo de empleado");
        modeloTabla.addColumn("Nombre del empleado");
        modeloTabla.addColumn("Sueldo de empleado");
        leerTexto();
    }
    
    
    private void leerTexto(){
        Empresa empresa1=new Empresa();
        for (int i = 0; i < empresa1.getNUMERO_EMPLEADOS(); i++) {
            String[] empleado={Integer.toString(empresa1.getCodigoDelEmpleado(i)),empresa1.getNombreDelEmpleado(i),Float.toString(empresa1.getSueldoDelEmpleado(i))};
            modeloTabla.addRow(empleado);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        SubMenu = new javax.swing.JMenu();
        ItemBurbuja = new javax.swing.JMenuItem();
        ItemInsersion = new javax.swing.JMenuItem();
        ItemSeleccion = new javax.swing.JMenuItem();
        ItemQuickShork = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LISTA DE TRABAJADORES POR DEFECTO");

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        BarraMenu.setBackground(new java.awt.Color(255, 255, 255));
        BarraMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BarraMenu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        SubMenu.setText("Ejercicios");
        SubMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        ItemBurbuja.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ItemBurbuja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        ItemBurbuja.setText("Ordenar por metodo burbuja");
        ItemBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBurbujaActionPerformed(evt);
            }
        });
        SubMenu.add(ItemBurbuja);

        ItemInsersion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ItemInsersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insertar.png"))); // NOI18N
        ItemInsersion.setText("Ordenar por metodo Insersion Directa");
        ItemInsersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemInsersionActionPerformed(evt);
            }
        });
        SubMenu.add(ItemInsersion);

        ItemSeleccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ItemSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grifo.png"))); // NOI18N
        ItemSeleccion.setText("Ordenar por metodo Seleccion Directa");
        ItemSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSeleccionActionPerformed(evt);
            }
        });
        SubMenu.add(ItemSeleccion);

        ItemQuickShork.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ItemQuickShork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/relampago.png"))); // NOI18N
        ItemQuickShork.setText("Ordenar por Quick-Sort");
        ItemQuickShork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQuickShorkActionPerformed(evt);
            }
        });
        SubMenu.add(ItemQuickShork);

        jMenuItem1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ideas.png"))); // NOI18N
        jMenuItem1.setText("COMPARAR TODOS LOS METODOS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        SubMenu.add(jMenuItem1);

        BarraMenu.add(SubMenu);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBurbujaActionPerformed
        VentanaBurbuja ventanaBurbuja=new VentanaBurbuja(this,true);
        ventanaBurbuja.setVisible(true);
        
    }//GEN-LAST:event_ItemBurbujaActionPerformed

    private void ItemInsersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemInsersionActionPerformed
        VentanaInsercion ventanaInsercion=new VentanaInsercion(this,true);
        ventanaInsercion.setVisible(true);
    }//GEN-LAST:event_ItemInsersionActionPerformed

    private void ItemSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSeleccionActionPerformed
        VentanaSeleccionDirecta ventanaSeleccionDirecta=new VentanaSeleccionDirecta(this, true);
        ventanaSeleccionDirecta.setVisible(true);
    }//GEN-LAST:event_ItemSeleccionActionPerformed

    private void ItemQuickShorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQuickShorkActionPerformed
        VentanaQuickSort ventanaQuickSort=new VentanaQuickSort(this,true);
        ventanaQuickSort.setVisible(true);
    }//GEN-LAST:event_ItemQuickShorkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ComparacionGeneral comparacionGeneral=new ComparacionGeneral(this,true);
        comparacionGeneral.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem ItemBurbuja;
    private javax.swing.JMenuItem ItemInsersion;
    private javax.swing.JMenuItem ItemQuickShork;
    private javax.swing.JMenuItem ItemSeleccion;
    private javax.swing.JMenu SubMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
