package pdinamica;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Eduar
 */
public class VentanaCoeficienteBinomial extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    public VentanaCoeficienteBinomial() {
        initComponents();
        jButton2.setVisible(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exponente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroCoeficiente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        etiquetaRecursivo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tiempoRecursividad = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etiquetaDinamico = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tiempoDinamica = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(0, 51, 51));
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("HALLANDO EL COEFICIENTE BINOMIAL");
        jPanel1.add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 930, 50));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("(A+B)");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 50));

        exponente.setBackground(new java.awt.Color(255, 204, 0));
        exponente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exponente.setForeground(new java.awt.Color(255, 51, 51));
        exponente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponenteActionPerformed(evt);
            }
        });
        jPanel2.add(exponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 200, 70));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("¿QUE TERMINO DESEAS?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        numeroCoeficiente.setBackground(new java.awt.Color(255, 204, 51));
        numeroCoeficiente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        numeroCoeficiente.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(numeroCoeficiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 60, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText(" DIGITA EL EXPONENTE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 130, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ANALISIS DE LA EFICIENCIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 930, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("DESPLIEGUE COMPLETO DEL BINOMIO");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable1.setModel(modelo);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.setAutoscrolls(false);
        jTable1.setRowHeight(20);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 640, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 940, 130));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaRecursivo.setBackground(new java.awt.Color(255, 153, 102));
        etiquetaRecursivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiquetaRecursivo.setForeground(new java.awt.Color(0, 153, 153));
        etiquetaRecursivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel5.add(etiquetaRecursivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TIEMPO EN NANOSEGUNDOS USANDO RECURSIVIDAD");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 40));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TIEMPO PARA LA OPERACION: ");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("COEFICIENTE BINOMIAL: ");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 20));

        tiempoRecursividad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tiempoRecursividad.setForeground(new java.awt.Color(0, 153, 153));
        jPanel5.add(tiempoRecursividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 230, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 430, 110));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TIEMPO EN NANOSEGUNDOS USANDO PRORAMACION DINAMICA");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TIEMPO PARA LA OPERACION: ");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, -1));

        etiquetaDinamico.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiquetaDinamico.setForeground(new java.awt.Color(0, 153, 153));
        etiquetaDinamico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel6.add(etiquetaDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 80, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("COEFICIENTE BINOMIAL: ");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, -1));

        tiempoDinamica.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tiempoDinamica.setForeground(new java.awt.Color(0, 153, 153));
        jPanel6.add(tiempoDinamica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 260, 20));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 470, 110));

        jButton2.setText("REINICIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exponenteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            CoeficientBinomial coeficientBinomial = new CoeficientBinomial();
            int n = Integer.parseInt(exponente.getText());
            int k = Integer.parseInt(numeroCoeficiente.getText()) - 1;
            if (n >= 0 && k>=0 && k<n+1) {
                long r1 = System.nanoTime();
                etiquetaRecursivo.setText(String.valueOf(coeficientBinomial.recursivo(n, k)));
                long r2 = System.nanoTime();
                long d1 = System.nanoTime();
                etiquetaDinamico.setText(String.valueOf(coeficientBinomial.dinamica(n, k)));
                long d2 = System.nanoTime();
                tiempoRecursividad.setText(String.valueOf((r2 - r1) + " nanoSegundos"));
                tiempoDinamica.setText(String.valueOf((d2 - d1) + " nanoSegundos"));
                cargarTabla(coeficientBinomial.dinamicaCompleta(n));
                jButton1.setVisible(false);
                jButton2.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "INGRESE VALORES VALIDOS \n INTENTE DE NUEVO");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "INGRESE VALORES VALIDOS \n INTENTE DE NUEVO");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        VentanaCoeficienteBinomial ventanaCoeficienteBinomial = new VentanaCoeficienteBinomial();
        ventanaCoeficienteBinomial.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cargarTabla(String[] contenido) {
        for (int i = 0; i < contenido.length; i++) {
            modelo.addColumn("TERMINO #" + (i + 1));
        }
        modelo.addRow(contenido);
        //Aumentar ancho columas si el resultado es muy grande
        if (contenido.length > 6) {
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumnModel columnModel = jTable1.getColumnModel();
            for (int i = 0; i < columnModel.getColumnCount(); i++) {
                columnModel.getColumn(i).setPreferredWidth(100);
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCoeficienteBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCoeficienteBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCoeficienteBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCoeficienteBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCoeficienteBinomial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaDinamico;
    private javax.swing.JLabel etiquetaRecursivo;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JTextField exponente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numeroCoeficiente;
    private javax.swing.JLabel tiempoDinamica;
    private javax.swing.JLabel tiempoRecursividad;
    // End of variables declaration//GEN-END:variables
}
