/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import dispersion.ReasignacionLineal;
import java.awt.Color;

/**
 *
 * @author Eduar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonLineal = new javax.swing.JButton();
        botonLineal1 = new javax.swing.JButton();
        botonCuadratico = new javax.swing.JButton();
        botonCuadratico1 = new javax.swing.JButton();
        botonDobleDireccion = new javax.swing.JButton();
        botonArregloAnidado = new javax.swing.JButton();
        botonEncadenamiento = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LABORATORIO 5 ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));

        botonLineal.setBackground(new java.awt.Color(255, 204, 0));
        botonLineal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonLineal.setText("REASIGNACION PRUEBA LINEAL");
        botonLineal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonLinealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonLinealMouseExited(evt);
            }
        });
        botonLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLinealActionPerformed(evt);
            }
        });
        jPanel1.add(botonLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        botonLineal1.setBackground(new java.awt.Color(255, 204, 0));
        botonLineal1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonLineal1.setText("REASIGNACION PRUEBA LINEAL CLAVE: NOMBRE ALUMNO");
        botonLineal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonLineal1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonLineal1MouseExited(evt);
            }
        });
        botonLineal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLineal1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLineal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        botonCuadratico.setBackground(new java.awt.Color(255, 204, 0));
        botonCuadratico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonCuadratico.setText("REASIGNACION PRUEBA CUADRATICA CLAVE: CODIGO");
        botonCuadratico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCuadraticoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCuadraticoMouseExited(evt);
            }
        });
        botonCuadratico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuadraticoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCuadratico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        botonCuadratico1.setBackground(new java.awt.Color(255, 204, 0));
        botonCuadratico1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonCuadratico1.setText("REASIGNACION PRUEBA CUADRATICA CLAVE: NOMBRE ALUMNO");
        botonCuadratico1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCuadratico1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCuadratico1MouseExited(evt);
            }
        });
        botonCuadratico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuadratico1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCuadratico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        botonDobleDireccion.setBackground(new java.awt.Color(255, 204, 0));
        botonDobleDireccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonDobleDireccion.setText("REASIGNACION DOBLE DIRECCION");
        botonDobleDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDobleDireccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDobleDireccionMouseExited(evt);
            }
        });
        botonDobleDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDobleDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(botonDobleDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        botonArregloAnidado.setBackground(new java.awt.Color(255, 204, 0));
        botonArregloAnidado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonArregloAnidado.setText("REASIGNACION ARREGLOS ANIDADOS");
        botonArregloAnidado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonArregloAnidadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonArregloAnidadoMouseExited(evt);
            }
        });
        botonArregloAnidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArregloAnidadoActionPerformed(evt);
            }
        });
        jPanel1.add(botonArregloAnidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        botonEncadenamiento.setBackground(new java.awt.Color(255, 204, 0));
        botonEncadenamiento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonEncadenamiento.setText("REASIGNACION ENCADENAMIENTO");
        botonEncadenamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEncadenamientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEncadenamientoMouseExited(evt);
            }
        });
        botonEncadenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEncadenamientoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEncadenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 580, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 580, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 580, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 580, 10));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDobleDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDobleDireccionActionPerformed
        DobleDireccion dobleDireccion=new DobleDireccion(this,true);
        dobleDireccion.setVisible(true);
    }//GEN-LAST:event_botonDobleDireccionActionPerformed

    private void botonArregloAnidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArregloAnidadoActionPerformed
        ArregloAnidado arregloAnidado=new ArregloAnidado(this,true);
        arregloAnidado.setVisible(true);
    }//GEN-LAST:event_botonArregloAnidadoActionPerformed

    private void botonEncadenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEncadenamientoActionPerformed
        Encadenamiento encadenamiento=new Encadenamiento(this,true);
        encadenamiento.setVisible(true);
    }//GEN-LAST:event_botonEncadenamientoActionPerformed

    private void botonCuadratico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuadratico1ActionPerformed
        CuadraticaNombre cuadraticaNombre=new CuadraticaNombre(this,true);
        cuadraticaNombre.setVisible(true);
    }//GEN-LAST:event_botonCuadratico1ActionPerformed

    private void botonCuadraticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuadraticoActionPerformed
        Cuadratica cuadratica=new Cuadratica(this,true);
        cuadratica.setVisible(true);
    }//GEN-LAST:event_botonCuadraticoActionPerformed

    private void botonLineal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLineal1ActionPerformed
        LinealClaveNombre linealClaveNombre=new LinealClaveNombre(this,true);
        linealClaveNombre.setVisible(true);
    }//GEN-LAST:event_botonLineal1ActionPerformed

    private void botonLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLinealActionPerformed
        Lineal lineal=new Lineal(this,true);
        lineal.setVisible(true);
    }//GEN-LAST:event_botonLinealActionPerformed

    private void botonCuadraticoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCuadraticoMouseEntered
        botonCuadratico.setBackground(Color.BLUE);
    }//GEN-LAST:event_botonCuadraticoMouseEntered

    private void botonCuadraticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCuadraticoMouseExited
        botonCuadratico.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_botonCuadraticoMouseExited

    private void botonCuadratico1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCuadratico1MouseEntered
        botonCuadratico1.setBackground(Color.BLUE);
    }//GEN-LAST:event_botonCuadratico1MouseEntered

    private void botonCuadratico1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCuadratico1MouseExited
        botonCuadratico1.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_botonCuadratico1MouseExited

    private void botonLinealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLinealMouseEntered
        botonLineal.setBackground(Color.BLUE);
    }//GEN-LAST:event_botonLinealMouseEntered

    private void botonLinealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLinealMouseExited
        botonLineal.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_botonLinealMouseExited

    private void botonLineal1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLineal1MouseEntered
        botonLineal1.setBackground(Color.BLUE);
    }//GEN-LAST:event_botonLineal1MouseEntered

    private void botonLineal1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLineal1MouseExited
        botonLineal1.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_botonLineal1MouseExited

    private void botonDobleDireccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDobleDireccionMouseEntered
        botonDobleDireccion.setBackground(Color.BLUE);
    }//GEN-LAST:event_botonDobleDireccionMouseEntered

    private void botonDobleDireccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDobleDireccionMouseExited
        botonDobleDireccion.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_botonDobleDireccionMouseExited

    private void botonArregloAnidadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonArregloAnidadoMouseEntered
        botonArregloAnidado.setBackground(Color.BLUE);
    }//GEN-LAST:event_botonArregloAnidadoMouseEntered

    private void botonArregloAnidadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonArregloAnidadoMouseExited
        botonArregloAnidado.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_botonArregloAnidadoMouseExited

    private void botonEncadenamientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEncadenamientoMouseEntered
        botonEncadenamiento.setBackground(Color.BLUE);
    }//GEN-LAST:event_botonEncadenamientoMouseEntered

    private void botonEncadenamientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEncadenamientoMouseExited
        botonEncadenamiento.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_botonEncadenamientoMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArregloAnidado;
    private javax.swing.JButton botonCuadratico;
    private javax.swing.JButton botonCuadratico1;
    private javax.swing.JButton botonDobleDireccion;
    private javax.swing.JButton botonEncadenamiento;
    private javax.swing.JButton botonLineal;
    private javax.swing.JButton botonLineal1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
